spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/thegrind
spring.datasource.username=root
spring.datasource.password=Tanu@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8081